stages:
  - train
  - report

variables:
  SUBJECT_NAME: tony  # the name of the person we want to train the model on
  SUBJECT_EXTRA: man
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # https://dvc.org/doc/user-guide/troubleshooting?tab=GitLab-CI-CD#git-shallow
  GIT_DEPTH: '0'

# https://pip.pypa.io/en/stable/reference/pip_install/#caching
cache:
  paths:
    - .cache/pip
    - models
    - data

train-job:
  stage: train
  image: nvidia/cuda:12.0.1-runtime-ubuntu22.04
  script:
    - nvidia-smi
    - sh ./scripts/installation.sh
    # setup credentials for s3 for dvc
    - dvc remote modify myremote access_key_id $MINIO_KEY_ID
    - dvc remote modify myremote secret_access_key $MINIO_ACCESS_KEY
    # pull data from s3
    - dvc pull
    # run experiment
    - dvc repro
  artifacts:
    expire_in: 1 week
    paths:
      - "./images"
report:
  stage: report
  image: iterativeai/cml:0-dvc2-base1
  needs:
    - job: train-job
      artifacts: true
  variables:
    REPO_TOKEN: $CML_PAT_TOKEN
  script:
    - sh ./scripts/report.sh