stages:
  prepare:
    cmd: python3 scripts/prepare.py
    deps:
    - data/images
    - scripts/prepare.py
    params:
    - prepare.size
    outs:
    - data/prepared
  train:
    cmd: sh scripts/train.sh
    deps:
    - data/prepared
    - scripts/train.sh
    params:
    - train.class_prompt
    - train.image_size
    - train.instance_prompt
    - train.learning_rate
    - train.model_name
    - train.steps
    - train.seed
    outs:
    - models
  infer:
    cmd: python3 scripts/infer.py
    deps:
    - models
    - scripts/infer.py
    params:
    - infer.prompt
    - infer.guidance
    - infer.infer_seed
    - infer.number_images
    - infer.steps
    outs:
    - images