stages:
  prepare:
    cmd: python3 scripts/prepare.py
    deps:
    - data/images
    - scripts/prepare.py
    params:
    - prepare.size
    outs:
    - data/prepared
  train:
    cmd: sh scripts/train.sh
    deps:
    - data/prepared
    - scripts/train.sh
    params:
    - train.class_prompt
    - train.image_size
    - train.instance_prompt
    - train.learning_rate
    - train.model_name
    - train.steps
    outs:
    - model
