# DO NOT USE - in names yq doesn't like it at all use single words and comment if needed
prepare:
  size: 512

train:
  size: 512
  steps: 600
  checkpoint: 210
  #Learning rate
  rate: 0.000002
  
infere:
  steps: 50
  guidance: 7.5
