apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-custom-runner
spec:
  replicas: 1
  repository: csia-pme/dreambooth-example-with-mlops
  template:
    spec:
      securityContext:
        # All level/role/type/user values will vary based on your SELinux policies.
        # See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/container_security_guide/docker_selinux_security_policy for information about SELinux with containers
        seLinuxOptions:
          level: "s0"
          role: "system_r"
          type: "super_t"
          user: "system_u"
      containers:
      - name: gpu-container
        image: nvidia/cuda:12.0.1-runtime-ubuntu22.04
        env: []
        resources:
          limits:
            nvidia.com/gpu: 1