apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: github-custom-runner
spec:
  repository: csia-pme/dreambooth-example-with-mlops
  containerMode: kubernetes
  serviceAccountName: default
  env: []
  resources:
    limits:
      nvidia.com/gpu: 1
  workVolumeClaimTemplate:
    storageClassName: "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 64Gi
  labels:
    - github-custom-runner