apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-binding
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-runner-role # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: github-runner-service-account # service account to bind to
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: github-custom-runner
spec:
  repository: csia-pme/dreambooth-example-with-mlops
  containerMode: kubernetes
  serviceAccountName: github-runner-service-account
  env: []
  resources:
    limits:
      nvidia.com/gpu: 1
  workVolumeClaimTemplate:
    storageClassName: "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 64Gi
  labels:
    - github-custom-runner