apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csia-pme-runner-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csia-pme-runner-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csia-pme-runner-binding
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csia-pme-runner-role # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: csia-pme-runner-service-account # service account to bind to
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: csia-pme-custom-runner
spec:
  replicas: 1
  template:
    spec:
      organization: csia-pme
      containerMode: kubernetes
      serviceAccountName: csia-pme-runner-service-account
      env: []
      resources:
        limits:
          nvidia.com/gpu: 1
      workVolumeClaimTemplate:
        storageClassName: "longhorn"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64Gi
      labels:
        - csia-pme-custom-runner
        - gpu