name: run-pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-job:
    runs-on: 
      group: csia-pme/default
      labels: [self-hosted, gpu]
    container:
      image: nvidia/cuda:12.0.1-runtime-ubuntu22.04
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
    steps:
      - name: GPU Info
        run: nvidia-smi
        # Update git as actions/checkout@v2 does not copy .git folder which is needed by dvc
      - name: Update Git
        run: |
          apt-get update
          apt-get install -y git
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sh ./scripts/installation.sh
      - name: Set up DVC credentials
        run: |
          dvc remote modify myremote access_key_id ${{ secrets.MINIO_KEY_ID }}
          dvc remote modify myremote secret_access_key ${{ secrets.MINIO_ACCESS_KEY }}
      - name: Pull data from S3
        run:  | 
          ls -la
          dvc pull
      - name: Run experiment
        run: dvc repro
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image-grid-artifact
          path: ./images
        env:
          retention-days: 7

  report:
    runs-on:
      group: csia-pme/default
      labels: [self-hosted, gpu]
    container:
      image: iterativeai/cml:0-dvc2-base1
    needs: train-job
    env:
      REPO_TOKEN: ${{ secrets.CML_PAT_TOKEN }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: image-grid-artifact
      - name: Run report
        run: |
          ls -la
          sh ./scripts/report.sh