name: run-pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-job:
    runs-on: [self-hosted, github-custom-runner]
    container:
      image: nvidia/cuda:12.0.1-runtime-ubuntu22.04
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
      GIT_DEPTH: '0'
    steps:
      - name: GPU Info
        run: nvidia-smi
      - name: Install dependencies
        run: sh ./scripts/installation.sh
      - name: Set up DVC credentials
        run: |
          dvc remote modify myremote access_key_id $MINIO_KEY_ID
          dvc remote modify myremote secret_access_key $MINIO_ACCESS_KEY
      - name: Pull data from S3
        run: dvc pull
      - name: Run experiment
        run: dvc repro
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Experiment artifacts
          path: ./images
        env:
          retention-days: 7

  report:
    runs-on: [self-hosted, github-custom-runner]
    container:
      image: iterativeai/cml:0-dvc2-base1
    needs: train-job
    env:
      REPO_TOKEN: ${{ secrets.CML_PAT_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Experiment artifacts
      - name: Run report
        run: sh ./scripts/report.sh